name: PenitenciaR
version: '1.0-SNAPSHOT'
main: org.imradigamer.chainPlugin.ChainPlugin
api-version: '1.21'
authors: [ ImRadiGamer ]
commands:
  chain:
    description: Control de las cadenas
    usage: /chain <origin|start|stop>
  camerashake:
    description: Activa el shake de la camara
    usage: /<command> shake
  elevator:
    description: Control del elevador
    usage: /<command> start
  glass:
    description: Rompe el cristal
    usage: /glass break
  doors:
    description: Controla las puertas
    usage: /doors <open|close>
  startblink:
    description: Starts the shader loop.
    usage: /startblink
  stopblink:
    description: Stops the shader loop.
    usage: /stopblink
  books:
    description: Control de los libros
    usage: /books
  hater:
    description: Control de las animaciones del hater
    usage: /hater
  lights:
    description: Control de las luces
    usage: /lights
  boots:
    description: Control de las botas
    usage: /boots
  bucket:
    description: Control de las cubetas
    usage: /bucket
  audio:
    description: Control de los casettes
    usage: /audio <restart>
  creditsred:
    description: Comienza los creditos para
    usage: /credits <nickname>
  creditsblack:
    description: Comienza los creditos para
    usage: /creditsblack <nickname>
  cajafuerte:
    description: Control de la caja fuerte
    usage: /safe restart
  circo:
    description: Controla las puertas del circo
    usage: /circo <1/2> <abrir/cerrar>
  day3:
    description: Comando del dia3
    usage: /day3
  jigsaw:
    description: Comando del Jigsaw
    usage: /day3
  enddoor:
    description: Controla la puerta del final
    usage: /enddoor
  resetenddoor:
    description: Controla la puerta del final
    usage: /enddoor
